#!/usr/local/bin/bash
prog=/usr/local/bin/vncpasswd
mypass=$(openssl rand -base64 32)

/usr/local/bin/expect <<EOF
spawn "$prog"
expect "Password:"
send "$mypass\r"
expect "Verify:"
send "$mypass\r"
expect "Would you like to enter a view-only password (y/n)?"
send "n\r"
expect eof
exit
EOF

echo "Password: "$mypass
vncserver -geometry 1366x768
